server:
  port: 8080

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://39.98.143.134:3306/ncth_student?useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true
    username: root
    password: abc.123
#    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      minimum-idle: 1
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 10000
      max-lifetime: 60000
      connection-timeout: 30000

#Mybatis-Plus配置
#mybatis-plus:
#  mapper-locations: classpath:mapper/*.xml
#  type-enums-package: com.soft1851.springboot.mbp.entity
#  global-config:
#    db-config:
#      #主键类型:auto主键自增，input用户输入id，id_worker全局唯一的数字id，UUID全局唯一的UUID
#      id-type: auto
#      #字段策略
#      #      field_strategy:not_empty
#      #开启驼峰转换
#      table-underline: true
#      db-type: mysql
